#!/usr/bin/env python

import sys
import gtk
import gtk.glade
import pygst
pygst.require("0.10")
import gst
import os

#
# Antar muka
#

def keluar(w):
	player.set_state(gst.STATE_NULL)
	gtk.main_quit()

def startstop(w=None):
	global mulai

	if mulai:
		player.set_state(gst.STATE_PAUSED)
		imgPutar.set_from_stock(gtk.STOCK_MEDIA_PLAY, gtk.ICON_SIZE_BUTTON)

	else:
		player.set_state(gst.STATE_PLAYING)
		imgPutar.set_from_stock(gtk.STOCK_MEDIA_PAUSE, gtk.ICON_SIZE_BUTTON)
	
	mulai = not mulai
	

glade = gtk.glade.XML("nontonfilm.glade")

window = glade.get_widget("window")
boxVideo = glade.get_widget("boxVideo")
btnPutar = glade.get_widget("btnPutar")
btnPilihFilm = glade.get_widget("btnPilihFilm")
sWaktu = glade.get_widget("sWaktu")
imgPutar = glade.get_widget("imgPutar")

layar = gtk.DrawingArea()
boxVideo.add(layar)

btnPutar.connect("clicked", startstop)
window.connect("destroy", keluar)

window.show_all()

mulai = False

#
# Gstreamer
#

def on_message(bus, message):
	t = message.type
	if t == gst.MESSAGE_EOS:
		player.set_state(gst.STATE_NULL)
	elif t == gst.MESSAGE_ERROR:
		player.set_state(gst.STATE_NULL)

def on_sync_message(bus, message):
	if message.structure is None:
		return
	message_name = message.structure.get_name()
	if message_name == "prepare-xwindow-id":
		imagesink = message.src
		imagesink.set_property("force-aspect-ratio", True)
		imagesink.set_xwindow_id(layar.window.xid)
			
player = gst.element_factory_make("playbin", "player")
bus = player.get_bus()
bus.add_signal_watch()
bus.enable_sync_message_emission()
bus.connect("message", on_message)
bus.connect("sync-message::element", on_sync_message)

#
# Pemutaran film
#

def putar(file):
	global mulai

	player.set_property("uri", "file://%s" % os.path.abspath(file))

	mulai = False
	startstop()


#
# Mulai
#

if len(sys.argv) > 1:
	putar(sys.argv[1])

gtk.gdk.threads_init()
gtk.main()

