#!/usr/bin/env python

import sys
import gtk
import gtk.glade
import pygst
pygst.require("0.10")
import gst
import os
import time
import thread

#
# Antar muka
#

def keluar(w):
	player.set_state(gst.STATE_NULL)
	gtk.main_quit()

def aturPosisi():
	global durasi, sWaktu

	while True:
		while not durasi:
			try:
				time.sleep(0.2)
				durasi = player.query_duration(time_format, None)[0]
				break
			except:
				pass
	
		sWaktu.set_range(0, durasi / 1000000)

		while durasi:
			time.sleep(1.0)

			posisi = player.query_position(time_format, None)[0]
			sWaktu.set_value(posisi / 1000000)



def startStop(w=None):
	global mulai, durasi

	if mulai:
		player.set_state(gst.STATE_PAUSED)
		imgPutar.set_from_stock(gtk.STOCK_MEDIA_PLAY, gtk.ICON_SIZE_BUTTON)

	else:
		player.set_state(gst.STATE_PLAYING)
		imgPutar.set_from_stock(gtk.STOCK_MEDIA_PAUSE, gtk.ICON_SIZE_BUTTON)

	mulai = not mulai

def ubahPosisi(w, scroll, value):
	posisi = sWaktu.get_value() * 1000000
	player.seek_simple(time_format, gst.SEEK_FLAG_FLUSH, posisi)

def pilihFilm(w):
	global fileFilm

	fc = gtk.FileChooserDialog("Pilih Film", buttons=(gtk.STOCK_CANCEL,gtk.RESPONSE_CANCEL,gtk.STOCK_OPEN,gtk.RESPONSE_OK))
	if fileFilm:
		print fileFilm
		dir = os.path.dirname(fileFilm)
		fc.set_current_folder(dir)

	res = fc.run()

	if res == gtk.RESPONSE_OK:
		putar(fc.get_filename())

	fc.destroy()


glade = gtk.glade.XML("nontonfilm.glade")

window = glade.get_widget("window")
boxVideo = glade.get_widget("boxVideo")
btnPutar = glade.get_widget("btnPutar")
btnPilihFilm = glade.get_widget("btnPilihFilm")
sWaktu = glade.get_widget("sWaktu")
imgPutar = glade.get_widget("imgPutar")

layar = gtk.DrawingArea()
boxVideo.add(layar)

btnPutar.connect("clicked", startStop)
window.connect("destroy", keluar)
sWaktu.connect("change-value", ubahPosisi)
btnPilihFilm.connect("clicked", pilihFilm)

window.show_all()

mulai = False
durasi = None
fileFilm = None

#
# Gstreamer
#

def on_message(bus, message):
	t = message.type
	if t == gst.MESSAGE_EOS:
		player.set_state(gst.STATE_NULL)
	elif t == gst.MESSAGE_ERROR:
		player.set_state(gst.STATE_NULL)

def on_sync_message(bus, message):
	if message.structure is None:
		return
	message_name = message.structure.get_name()
	if message_name == "prepare-xwindow-id":
		imagesink = message.src
		imagesink.set_property("force-aspect-ratio", True)
		imagesink.set_xwindow_id(layar.window.xid)
			
player = gst.element_factory_make("playbin", "player")
bus = player.get_bus()
bus.add_signal_watch()
bus.enable_sync_message_emission()
bus.connect("message", on_message)
bus.connect("sync-message::element", on_sync_message)

time_format = gst.Format(gst.FORMAT_TIME)

#
# Pemutaran film
#

aturPosisiId = None

def putar(file):
	global mulai, durasi, fileFilm, aturPosisiId

	fileFilm = file
	player.set_property("uri", "file://%s" % os.path.abspath(file))

	mulai = False
	durasi = None
	player.set_state(gst.STATE_NULL)

	if not aturPosisiId:
		aturPosisiId = thread.start_new_thread(aturPosisi, ())

	startStop()


#
# Mulai
#

if len(sys.argv) > 1:
	putar(sys.argv[1])

gtk.gdk.threads_init()
gtk.main()

